;SDL

{weapon "bomb-dropper"
	{type bombing}
	{foresight "pivot_front"}
	{item "air bomb"
	}
	{recoveryTime 0.5}			; s
	{rechargeTime 5.0}			; s
	{automatic}
	{aimRange 9999999999}
}
{weapon "bomb-dropper2"
	{type bombing}
	{foresight "pivot_front"}
	{item "air bomb"
	}
	{recoveryTime 0.5}			; s
	{rechargeTime 5.0}			; s
	{automatic}
	{aimRange 9999999999}
}
{ammo "air bomb"
}
{weapon "bomb-dropper3"
	{type bombing}
	{foresight "pivot_front"}
	{item "napalm"
	}
	{recoveryTime 0.5}			; s
	{rechargeTime 5.0}			; s
	{automatic}
	{aimRange 9999999999}
}
{ammo "napalm"
}
