{ammo "mine antipersonnel"
	{damage blastwave
		{energy 2}
		{area 4 6}
	}
}
{ammo "mine antitank"
	{damage blastwave
		{energy 15.5}
		{area 3 6}
	}
}
{ammo "dynamite"
	{damage blastwave
		{energy 20}
		{area 4 9}
	}
}
{ammo "tnt"
	{damage blastwave
		{energy 11}
		{area 2 2}
	}
}
{ammo "oz"
	{damage blastwave
		{energy 8}
		{area 2 2}
	}
}
{ammo "eg"
	{damage blastwave
		{energy 0}
		{area 0 0}
	}
}
{ammo "wires"
	{damage blastwave
		{energy 0}
		{area 0 0}
	}
}
{ammo "pala"
	{damage blastwave
		{energy 0}
		{area 0 0}
	}
}
{ammo "jap_mt_box"
	{damage blastwave
		{energy 0}
		{area 0 0}
	}
}
{ammo "jap_mg_box"
	{damage blastwave
		{energy 0}
		{area 0 0}
	}
}
{ammo "usa_mt_box"
	{damage blastwave
		{energy 0}
		{area 0 0}
	}
}
{ammo "usa_mg_box"
	{damage blastwave
		{energy 0}
		{area 0 0}
	}
}
{ammo "uk_mt_box"
	{damage blastwave
		{energy 0}
		{area 0 0}
	}
}
{ammo "uk_mg_box"
	{damage blastwave
		{energy 0}
		{area 0 0}
	}
}
