;SDL

{weapon "mg34_2" from "mg34"
	{fireSound	"mgun_shot.mgcoax"}
	{foresight "Foresight2"}
	{reloadSound "reload.mg1_r"}
	{maxRange 150}					; m
        {cursor "/interface/cursor/mgun_on_2.ebm"}
	(mod "mp"
		{maxRange 150}					; m
	)
}
{weapon "mg42_2" from "mg34"
	{fireSound	"mgun_shot.mgcoax"}
	{foresight "Foresight2"}
	{reloadSound "reload.mg1_r"}
	{maxRange 150}					; m
        {cursor "/interface/cursor/mgun_on_2.ebm"}
	(mod "mp"
		{maxRange 150}					; m
	)
}
{weapon "dt_2" from "dt"
	{fireSound	"mgun_shot.dtcoax"}
	{foresight "Foresight2"}
	{reloadSound "reload.dt1_r"}
	{maxRange 150}					; m
        {cursor "/interface/cursor/mgun_on_2.ebm"}
	(mod "mp"
		{maxRange 150}					; m
	)
}
{weapon "browning_2" from "browning"
	{fireSound	"mgun_shot.browningcoax"}
	{foresight "Foresight2"}
	{reloadSound "reload.mg1_r"}
	{maxRange 150}					; m
        {cursor "/interface/cursor/mgun_on_2.ebm"}
	(mod "mp"
		{maxRange 150}					; m
	)
}
{weapon "besa_2" from "besa"
	{fireSound	"mgun_shot.besacoax"}
	{foresight "Foresight2"}
	{reloadSound "reload.mg1_r"}
	{maxRange 150}					; m
        {cursor "/interface/cursor/mgun_on_2.ebm"}
	(mod "mp"
		{maxRange 150}					; m
	)
}
{weapon "wz33_2" from "dt"
	{fireSound	"mgun_shot.dt"}
	{foresight "Foresight2"}
	{reloadSound "reload.dt1_r"}
	{maxRange 150}					; m
        {cursor "/interface/cursor/mgun_on_2.ebm"}
	(mod "mp"
		{maxRange 150}					; m
	)
}
{weapon "type99_2" from "type99"
	{fireSound	"mgun_shot.type99"}
	{foresight "Foresight2"}
        {cursor "/interface/cursor/mgun_on_2.ebm"}
	(mod "mp"
		{maxRange 150}					; m
	)
}
{weapon "type97_2" from "type97"
	{fireSound	"mgun_shot.type99"}
	{foresight "Foresight2"}
        {cursor "/interface/cursor/mgun_on_2.ebm"}
	(mod "mp"
		{maxRange 150}					; m
	)
}
{weapon "type1hmg_2" from "type1hmg"
	{fireSound	"mgun_shot.mle"}
	{foresight "Foresight2"}
        {cursor "/interface/cursor/mgun_on_2.ebm"}
	(mod "mp"
		{maxRange 150}					; m
	)
}
{weapon "DSHK_2" from "DSHK"
	{fireSound	"mgun_shot.DSHK"}
        {foresight "Foresight2"}
	{reloadSound "reload.mg1_r"}
	{maxRange 160}
	{foresight "Foresight2"}
        {cursor "/interface/cursor/mgun_on_3.ebm"}
	(mod "mp"
		{maxRange 160}					; m
	)
}
{weapon "50cal_2" from "50cal"
	{fireSound	"mgun_shot.50cal"}
        {foresight "Foresight2"}
	{reloadSound "reload.mg1_r"}
	{maxRange 160}
	{foresight "Foresight2"}
        {cursor "/interface/cursor/mgun_on_3.ebm"}
	(mod "mp"
		{maxRange 160}					; m
	)
}
{weapon "bigflamethrower_2" from "DSHK"
	{fireSound	"mgun_shot.DSHK"}
        {foresight "Foresight2"}
	{reloadSound "mgun_reload.mg34"}
	{foresight "Foresight2"}
}
