;SDL
{"pistol_shot"
	{tag "effects"}
	{loudness "shoot normal"}
	{file "/sound/shot/pistol/luger.WAV"		"luger"		}
	{file "/sound/shot/pistol/colt45.WAV"		"colt"		}
	{file "/sound/shot/pistol/valter.WAV"		"valter"	}
	{file "/sound/shot/pistol/nagan.WAV"		"nagan"		}
	{file "/sound/shot/pistol/tt.WAV"			"tt"		}
        {file "/sound/shot/pistol/webley.WAV"		"webley"		}
        {file "/sound/shot/pistol/mle1935a.WAV"		"mle1935a"		}
		{file "/sound/shot/pistol/nambu.WAV"		"nambu"		}
		{file "/sound/shot/pistol/type26.WAV"		"type26"	}
		{file "/sound/shot/pistol/c96.WAV"		"c96"		}
        {file "/sound/shot/pistol/type94.WAV"		"type94"	}
	{signal shot 15}
}
{"pistol_shot_silent"
	{tag "effects"}
	{loudness "shoot muted"}
	{file "/sound/shot/pistol/welrod.WAV"		"welrod"	}
        {file "/sound/shot/pistol/welrod2.WAV"		"welrod2"	}
	{signal movement 5}
}
{"smg_shot"
	{tag "effects"}
	{loudness "shoot normal"}
	{file "/sound/shot/smg/mp38.WAV"			"mp38"		}
	{file "/sound/shot/smg/mp40.WAV"			"mp40"		}
        {file "/sound/shot/smg/mp40_I.WAV"			"mp40_I"	}
	{file "/sound/shot/smg/sten.WAV"			"sten"		}
	{file "/sound/shot/smg/stenmk5.WAV"			"stenmk5"	}
	{file "/sound/shot/smg/mp41.WAV"			"mp41"		}
	{file "/sound/shot/smg/mp44.WAV"			"mp44"		}
	{file "/sound/shot/smg/ppsh.WAV"			"ppsh"		}
        {file "/sound/shot/smg/pps.WAV"			"pps"		}
        {file "/sound/shot/smg/ppsh2.WAV"			"ppsh2"		}
        {file "/sound/shot/smg/m3a.WAV"			"m3a"		}
	{file "/sound/shot/smg/thompson.WAV"		"thompson"	}
        {file "/sound/shot/smg/volksgewehr.WAV"		"volksgewehr"		}
        {file "/sound/shot/smg/mas1938.WAV"		"mas1938"		}
	{file "/sound/shot/gun/grnd_launch.wav"		"grenade"	}
        {file "/sound/shot/gun/grnd_launch_2.wav"		"grenade_2"	}
	{file "/sound/shot/gun/shotgun.wav"			"shotgun"	}
	{file "/sound/shot/smg/t100.WAV"		"t100"		}
	{file "/sound/shot/gun/winchester1912.wav"	"winchester"	}
        {file "/sound/shot/smg/tommy.WAV"		"tommy"		}
        {file "/sound/shot/smg/type2smg.WAV"		"t2"		}
	{signal shot 20}
}
{"mgun_shot"
	{tag "effects"}
	{loudness "shoot normal"}
	{file "/sound/shot/mgun/dt.WAV"				"dt"		}
	{file "/sound/shot/mgun/dtcoax.WAV"			"dtcoax"	}
	{file "/sound/shot/mgun/mg.WAV"				"mg34"		}
	{file "/sound/shot/mgun/mgcoax.WAV"			"mgcoax"	}
	{file "/sound/shot/mgun/mg_1.WAV"			"mg42"		}
	{file "/sound/shot/mgun/browning.WAV" 			"browning"	}
	{file "/sound/shot/mgun/browningcoax.WAV" 		"browningcoax"	}
	{file "/sound/shot/mgun/mle.WAV" 			"mle"		}
	{file "/sound/shot/mgun/bren.WAV" 			"bren"		}
        {file "/sound/shot/mgun/besa.WAV" 			"besa"		}
        {file "/sound/shot/mgun/besacoax.WAV" 			"besacoax"	}
        {file "/sound/shot/mgun/vickers.wav" 			"vickers"       } 
	{file "/sound/shot/mgun/bar.WAV" 			"bar"		}
        {file "/sound/shot/mgun/Jonson.WAV"             "johnsonlightgun"       }
        {file "/sound/shot/mgun/ZB-26-30.WAV"                  "ZB-26-30"       } 
        {file "/sound/shot/mgun/DSHK.WAV"                   "DSHK"       }
        {file "/sound/shot/mgun/50cal.WAV"                   "50cal"       }
        {file "/sound/shot/mgun/rpd.WAV"                   "rpd"       }
        {file "/sound/shot/mgun/mg_13.WAV"                   "MG13"       }
        {file "/sound/shot/mgun/maxim.WAV"                   "maxim"       }
        {file "/sound/shot/mgun/reibel.WAV"                   "reibel"       }
        {file "/sound/shot/mgun/chm1924.WAV"                   "chm1924"       }
	    {file "/sound/shot/mgun/type99.WAV"		"type99"		}
        {file "/sound/shot/mgun/type93.WAV"		"type93"		}
        {file "/sound/shot/mgun/lewis.WAV"		"lewis"			}
	{signal shot 30}
}
{"rifle_shot"
	{tag "effects"}
	{loudness "shoot loud"}
	{file "/sound/shot/rifle/carabine.WAV"		"carabine"	}
	{file "/sound/shot/rifle/svt.WAV"			"svt"		}
        {file "/sound/shot/rifle/svt2.WAV"			"svt2"		}
        {file "/sound/shot/rifle/avs.WAV"			"avs"		}
	{file "/sound/shot/rifle/mosin.WAV"			"mosin"		}
	{file "/sound/shot/rifle/mauser98.WAV"		"mauzer"	}
	{file "/sound/shot/rifle/wz98.wav"		"wz98"	}
	{file "/sound/shot/rifle/G41.WAV"			"g41"		}
        {file "/sound/shot/rifle/k43.WAV"			"k43"		}
	{file "/sound/shot/rifle/m1.WAV" 			"m1"		}
	{file "/sound/shot/rifle/m1carbine.WAV" 	"m1carbine"	}
	{file "/sound/shot/rifle/ptrs.wav"			"ptrs"		}
        {file "/sound/shot/rifle/pzb39.wav"			"pzb39"		}
	{file "/sound/shot/rifle/enfield.wav"		"enfield"	}
	{file "/sound/shot/rifle/enfield2.wav"		"enfield2"	}
	{file "/sound/shot/rifle/m1903a4.wav"		"m1903a4"	}
        {file "/sound/shot/rifle/Jonson.WAV"             "johnson1941"       }
        {file "/sound/shot/rifle/fg42.WAV"               "fg42"       }
        {file "/sound/shot/rifle/Springfield.wav"	"Springfield"	}
        {file "/sound/shot/rifle/mas.wav"	         "mas36_51"	}
		{file "/sound/shot/rifle/arisaka.wav"		"arisaka"	}
        {file "/sound/shot/rifle/arisakasc.wav"		"arisakasc"	}
        {file "/sound/shot/rifle/type5.wav"		"type5"		}
        {file "/sound/shot/rifle/mosin_scp.wav"		"mosin2"	}
        {file "/sound/shot/rifle/type38.wav"		"type38"		}
	{signal shot 25}
}
{"flamethrower_shot_muted"
	{tag "effects"}
	{loudness "shoot muted"}
	{file "/sound/shot/flamethrower.WAV"		"flamethrower"	}
	{signal movement 7}
}
{"heavy_shot"
	{tag "effects"}
	{loudness "shoot loud"}
	{file "/sound/shot/gun/zis3.wav"			"cannon"	}
	{file "/sound/Shot/gun/sam.wav"			"37mm"		}
	{file "/sound/Shot/gun/shot07.wav"				"20mm"	}
        {file "/sound/Shot/gun/shot08.wav"			"20mm_tnsh"	}   
	{file "/sound/Shot/gun/shot03.wav"			"45mm"		}
	{file "/sound/Shot/gun/45mm_53k.wav"			"45mm_53k"	}
	{file "/sound/Shot/gun/45mm_m42.wav"			"45mm_m42"	}
	{file "/sound/Shot/gun/shot10.wav"			"47mm"		}
	{file "/sound/Shot/gun/shot.wav"			"50mm"		}
	{file "/sound/Shot/gun/shot75.wav"			"75mm"		}
	{file "/sound/Shot/gun/shot05.wav"			"76mm"		}
	{file "/sound/Shot/gun/zis3.wav"			"76a_mm"	}
	{file "/sound/Shot/gun/shot02.wav"			"85mm"		}
	{file "/sound/Shot/gun/shot88.wav"			"88mm"		}
	{file "/sound/Shot/gun/shot04.wav"			"105mm"		}
	{file "/sound/Shot/gun/shot01.wav"			"122mm"		}
	{file "/sound/Shot/gun/shot150.wav"			"152mm"		}
	{file "/sound/Shot/gun/shot150.wav"			"150mm"		}
	{file "/sound/Shot/gun/bm-13.wav"			"bm13"		}
	{file "/sound/Shot/gun/coastmortar.wav"		"203mm"		}
        {file "/sound/Shot/gun/mortar_80.wav"		"mortar_120"		} 
        {file "/sound/Shot/gun/mortar.wav"		"mortar_80"		}  
     {file "/sound/Shot/gun/37mm_type94.wav"			"37mmj"		}
	{file "/sound/Shot/gun/47mm_type1.wav"			"47mmj"		}
	{file "/sound/Shot/gun/57mm.wav"			"57mmj"		}
	{file "/sound/Shot/gun/75mm_type5.wav"			"75mmj1"	}
	{file "/sound/Shot/gun/75mm_type99.wav"			"75mmj2"	}
	{file "/sound/Shot/gun/75mm_type3.wav"			"75mmj3"	}
	{file "/sound/Shot/gun/75mm_type90.wav"			"75mmj4"	}
	{file "/sound/Shot/gun/88mm_type99.wav"			"88mmj"		}
	{file "/sound/Shot/gun/105mm_type91.wav"		"105mmj"	}
	{file "/sound/Shot/gun/105mm_type6.wav"			"105mmatj"	}
	{file "/sound/Shot/gun/120mm_type10.wav"		"120mmj"	}
	{file "/sound/Shot/gun/150mm_type38.wav"		"150mmj"	}
        {file "/sound/Shot/gun/type4_200.wav"			"type4_200"	}
        {file "/sound/Shot/gun/shot40.wav"			"40mm"		}
        {file "/sound/Shot/gun/shot57.wav"			"57mm"		}
        {file "/sound/Shot/gun/shot50.wav"			"50mm"		}
	{file "/sound/Shot/gun/shot.wav"			"gun"		}		
	{signal shot 70}
}
{"reload"
	{tag "effects"}
	{loudness "reload"}
	{file "/sound/reload/gun/smg.WAV"			"smg"		}
	{file "/sound/reload/gun/colt_r.WAV"		"colt_r"	}
	{file "/sound/reload/gun/sten_r.WAV"		"sten_r"	}
	{file "/sound/reload/gun/bar_r.WAV"			"bar_r"		}
	{file "/sound/reload/gun/rifle_r.WAV"		"rifle"		}
	{file "/sound/reload/gun/mauzer_r.WAV"		"mauzer_r"	}
	{file "/sound/reload/gun/mosin_r.WAV"		"mosin_r"	}
	{file "/sound/reload/gun/enfield_r.WAV"		"enfield_r"	}
	{file "/sound/reload/gun/mg1_r.WAV"			"mg1_r"		}
	{file "/sound/reload/gun/mg2_r.WAV"			"mg2_r"		}
	{file "/sound/reload/gun/dt1_r.WAV"			"dt1_r"		}
	{file "/sound/reload/gun/mp44_r.WAV"		"mp44_r"	}
	{file "/sound/reload/gun/m1_r.WAV"			"m1_r"		}
	{file "/sound/reload/gun/m1carbine_r.WAV"	"m1carbine_r"}
	{file "/sound/reload/gun/welrod_r.WAV"		"welrod_r"	}
	{file "/sound/reload/gun/pistol_r.WAV"		"pistol_r"	}
	{file "/sound/reload/gun/nagan_r.WAV"		"nagan_r"	}
	{file "/sound/reload/gun/webley_r.WAV"		"webley_r"	}
	{file "/sound/reload/gun/pak35_r.WAV"		"pak35_r"	}
	{file "/sound/reload/gun/ppsh_r.WAV"		"ppsh_r"	}
	{file "/sound/reload/gun/flak38_r.WAV"		"flak38_r"	}
	{file "/sound/reload/gun/ptrd_r.WAV"		"ptrd_r"	}
	{file "/sound/reload/gun/ptrs_r.WAV"		"ptrs_r"	}
	{file "/sound/reload/gun/gun_r00.WAV"		"gun_r00"	}
	{file "/sound/reload/gun/gun_r01.WAV"		"gun_r01"	}
	{file "/sound/reload/gun/gun_r02.WAV"		"gun_r02"	}
	{file "/sound/reload/gun/gun_r03.WAV"		"gun_r03"	}
	{file "/sound/reload/gun/flame_r.WAV"		"flame_r"	}
	{file "/sound/reload/gun/shotgun_r.wav"		"shotgun_r"	}
	{file "/sound/reload/gun/lewis_r.wav"		"lewis_r"	}
	{file "/sound/reload/gun/winchester_r.wav"	"winchester_r"	}
	{file "/sound/reload/gun/c96_r.WAV"		"c96_r"	}
}
