{cm_city
	{name 		"OnlyInf_city"}
	{location 	"multi\city:cm"}
	{game 		"combat"}
	{maxPlayers "16"}
	{maxUnits 	"7"}
	{deathmatch "0"}
	{balance 	"900"}
	{teams
		{x "mp_settings/teamx"
			{maxPlayers "8"}
		}
		{z "mp_settings/teamz"
			{maxPlayers "8"}
		}
	}
}
{as_city
	{name 		"city"}
	{location 	"multi\city:as"}
	{game 		"assault"}
	{maxUnits 	"10"}
	{balance 	"900"}
	{zone		"zone"}
	{teams
		{a "mp_settings/teama"}
		{d "mp_settings/teamd"}
	}
}

