;SDL
{"cow_moo"
	{tag "environment"}
	{file "/sound/animal/cow/cow_moo_00.WAV"}
	{file "/sound/animal/cow/cow_moo_01.WAV"}
	{file "/sound/animal/cow/cow_moo_02.WAV"}
	{file "/sound/animal/cow/cow_moo_03.WAV"}
}
{"dog_aw"
	{tag "environment"}
	{file "/sound/animal/dog/dog_aw_00.WAV"}
	{file "/sound/animal/dog/dog_aw_01.WAV"}
	{file "/sound/animal/dog/dog_aw_02.WAV"}
	{file "/sound/animal/dog/dog_aw_03.WAV"}
	{file "/sound/animal/dog/dog_aw_04.WAV"}
	{file "/sound/animal/dog/dog_cry.WAV"}
}
{"chicken_clucking"
	{tag "environment"}
	{file "/sound/animal/chicken/chick1.wav"}
	{file "/sound/animal/chicken/chick2.wav"}
	{file "/sound/animal/chicken/chick3.wav"}
	{file "/sound/animal/chicken/chick4.wav"}
	{file "/sound/animal/chicken/chick5.wav"}
	{file "/sound/animal/chicken/chick6.wav"}
}	
{"animal_die"
	{tag "environment"}
	{file "/sound/animal/chicken/killchicken.wav"	"chicken"	}
	{file "/sound/animal/dog/dogdies.wav"			"dog"		}
}
