;SDL
{"fire"
	{tag "environment"}
	{file "/sound/Fire/fire_big.wav"	"big"		}
	{file "/sound/Fire/fire_big1.wav"	"big1"		}
	{file "/sound/Fire/fire_med.wav"	"med"		}
}
{"water"
	{tag "environment"}
	{file "/sound/water/water_bloop_bul1.wav"		}
	{file "/sound/water/water_bloop_bul2.wav"		}
	{file "/sound/water/water_bloop_bul3.wav"		}
	{file "/sound/water/water_bloop_bul4.wav"		}
	{file "/sound/water/water_bloop_bul5.wav"		}
	{file "/sound/water/water_bloop_bul6.wav"		}
	{file "/sound/water/water_bloop_bul7.wav"		}
	{file "/sound/water/water_bloop_bul8.wav"		}
	{file "/sound/water/water_bloop_bul9.wav"		}
}
{"world"
	{tag "environment"}
	{file "/SOUND/world/nature.WAV"			"nature"	}
	{file "/SOUND/world/sirene00.wav"		"sirene00"	}
	{file "/SOUND/world/sirene01.wav"		"sirene01"	}
	{file "/SOUND/world/alarm.wav"			"alarm"		}
	{file "/SOUND/world/FOUNTAIN.WAV"		"fountain"	}
	{file "/SOUND/world/crows.WAV"			"crows"		}
	{file "/SOUND/world/sparrow.WAV"		"sparrow"	{volume 0.2}}
	{file "/SOUND/world/torn_Bomb1.WAV"		"bomb1"		}
	{file "/SOUND/world/torn_Bomb2.WAV"		"bomb2"		}
	{file "/SOUND/world/BIRDS01.WAV"		"birds01"	}
	{file "/SOUND/world/BIRDS02.WAV"		"birds02"	}
	{file "/SOUND/world/BIRDS03.WAV"		"birds03"	}
	{file "/SOUND/world/Lake.WAV"			"lake"		}
	{file "/SOUND/world/point.WAV"			"point"		}
	{file "/SOUND/world/seawave_am.wav"		"waves_am"	}
	{file "/SOUND/world/seawave_pm.wav"		"waves_pm"	}
	{file "/SOUND/world/summernight.wav"	"sum_night"	{volume 0.5}}
	{file "/SOUND/world/summernight01.wav"	"sum_night01"}
	{file "/SOUND/world/summernight02.wav"	"sum_night02"}
	{file "/SOUND/world/summernight03.wav"	"sum_night03"}
	{file "/SOUND/world/rain01.wav"			"rain_noise"{volume 0.2}}
	{file "/SOUND/world/canonade03.wav"		"thunder"	}
	{file "/SOUND/world/nature.WAV"		    "nature"	}
	{file "/SOUND/world/village.WAV"		"chepel"	}
	{file "/SOUND/world/BIRDS8.WAV"		    "birds8"	{volume 0.1}}
	{file "/SOUND/world/training.wav"		"training"	}
	{file "/SOUND/world/run.wav"				"run"	}
	{file "/SOUND/world/coupling.wav"		"tr_stack"	}
}
{"battle"
	{loudness "canonade"}
	{tag "main_environment"}
	{file "/SOUND/world/canonade00.WAV"			"can00"	}
	{file "/SOUND/world/canonade01.WAV"			"can01"	}
	{file "/SOUND/world/canonade02.WAV"			"can02"	}
	{file "/SOUND/world/canonade03.WAV"			"can03"	}
	{file "/SOUND/world/canonade04.WAV"			"can04"	}
	{file "/SOUND/world/canonade04.WAV"			"can04"	}
	{file "/SOUND/world/wint_battle.wav"		"can05"	}
	{file "/SOUND/world/landing01.wav"			"land01"}
	{file "/SOUND/world/landing02.wav"			"land02"}
	{file "/SOUND/world/landing03.wav"			"land03"}
	{file "/SOUND/world/landing04.wav"			"land04"}
	{file "/SOUND/world/landing05.wav"			"land05"}
	{file "/SOUND/world/landing06.wav"			"land06"}
	{file "/SOUND/world/launch01.wav"		  "launch01"}
	{file "/SOUND/world/plane_crush00.wav"	"pl_crush00"}
	{file "/SOUND/world/plane_crush01.wav"	"pl_crush01"}
}
