;SDL
{"small_explosion"
	{tag "effects"}
	{loudness "blast small"}
	{file "/SOUND/EXPLOSION/expl.wav"		"0"		}
	{signal explosion 10}
}
{"explosion"
	{tag "effects"}
	{loudness "blast big"}

	{file "/SOUND/EXPLOSION/expl.wav"		"0"		}
	{file "/SOUND/EXPLOSION/sm_grnd.WAV"   "sm_grnd"}
	{file "/SOUND/EXPLOSION/at_grnd.WAV"   "at_grnd"}
	{file "/SOUND/EXPLOSION/EXPKAMI.WAV"	"big"	}
	{file "/SOUND/EXPLOSION/expl_water.wav"	"water"	}
	{file "/SOUND/EXPLOSION/expl_metal.wav"	"metal"	}
	{file "/SOUND/EXPLOSION/vehic_die.wav"	"tank"	}
	{file "/SOUND/EXPLOSION/vehic_die1.wav"	"car"	}
	{file "/SOUND/EXPLOSION/exp_flour.wav"	"sack"	}
	{file "/SOUND/EXPLOSION/airbomb.wav"	"air_bomb"}
	{signal explosion 20}
}
