;SDL
{"hit"
	{tag "effects"}
	{loudness "hit"}
	{file "/SOUND/HIT/hit_water.wav"		"water"	}
	{file "/SOUND/HIT/hit_ground.wav"		"ground"}
	{file "/SOUND/HIT/ground_hit.wav"		"med_hit"}
}
{"small_hit"
	{tag "effects"}
	{loudness "hit"}
   	{file "/SOUND/hit/small_hit0.wav"}
	{file "/SOUND/hit/small_hit2.wav"}
	{file "/SOUND/hit/small_hit3.wav"}
	{file "/SOUND/hit/small_hit5.wav"}
	{file "/SOUND/hit/small_hit6.wav"}
	{file "/SOUND/hit/small_hit7.wav"}
	{file "/SOUND/hit/small_hit8.wav"}
	{file "/SOUND/hit/small_hit9.wav"}
	{file "/SOUND/hit/small_hit10.wav"}
	{file "/SOUND/hit/small_hit11.wav"}
	{file "/SOUND/hit/small_hit12.wav"}
	{file "/SOUND/hit/small_hit13.wav"}
	{file "/SOUND/hit/small_hit14.wav"}
	{file "/SOUND/hit/small_hit15.wav"}
	{file "/SOUND/hit/small_hit16.wav"}
	{file "/SOUND/hit/small_hit17.wav"}
	{file "/SOUND/hit/small_hit18.wav"}
	{file "/SOUND/hit/small_hit19.wav"}
	{file "/SOUND/hit/small_hit20.wav"}
	{file "/SOUND/hit/small_hit21.wav"}
	{signal hit 5}
}	
{"hit_metall"
	{tag "effects"}
	{loudness "hit"}
	{file "/SOUND/hit/hit_metal/ric_metall_shell.wav"	 "0"}
	{file "/SOUND/hit/hit_metal/ric_metall_bullet0.wav"	 "1"}
	{file "/SOUND/hit/hit_metal/ric_metall_bullet3.wav"	 "2"}
	{file "/SOUND/hit/hit_metal/ric_metall_bullet4.wav"	 "3"}
	{file "/SOUND/hit/hit_metal/ric_metall_bullet5.wav"	 "4"}
	{file "/SOUND/hit/hit_metal/ric_metall_bullet6.wav"	 "5"}
	{file "/SOUND/hit/hit_metal/ric_metall_bullet7.wav"	 "6"}
	{file "/SOUND/hit/hit_metal/ric_metall_bullet8.wav"	 "7"}
	{file "/SOUND/hit/hit_metal/ric_metall_bullet9.wav"	 "8"}
	{file "/SOUND/hit/hit_metal/ric_metall_bullet10.wav" "9"}
	{file "/SOUND/hit/hit_metal/ric_metall_bullet11.wav""11"}
	{file "/SOUND/hit/hit_metal/ric_metall_bullet1.wav"	"12"}
	{file "/SOUND/hit/hit_metal/ric_metall_bullet2.wav"	"13"}
	{file "/SOUND/hit/hit_metal/ric_metall_shell1.wav"	"14"}
	{file "/SOUND/hit/small_hit6.wav"     				"15"}
	{file "/SOUND/hit/small_hit8.wav"     				"16"}
	{signal hit 10}
}	
{"hit_glass"
	{tag "effects"}
	{loudness "hit"}
	{file "/SOUND/hit/glass_sm.wav"		 "0"}
	{file "/SOUND/hit/glass_med.wav"	 "1"}
	{file "/SOUND/hit/glass_b.wav"	     "2"}
	{signal hit 10}
}	
{"ricochet"
	{tag "effects"}
	{loudness "hit"}
	{file "/SOUND/Ricochet/ricochet.wav"			"0"}
	{file "/SOUND/Ricochet/ricochet1.wav"			"1"}
	{file "/SOUND/Ricochet/ricochet2.wav"			"2"}
	{file "/SOUND/Ricochet/ricochet5.wav"			"5"}
	{file "/SOUND/Ricochet/ricochet6.wav"			"6"}
	{file "/SOUND/Ricochet/ricochet8.wav"			"8"}
	{file "/SOUND/Ricochet/ric_wood_bullet1.wav"	"9"}
	{file "/SOUND/Ricochet/ric_wood_bullet2.wav"	"10"}
	{signal hit 10}
}
{"hit_tree"
	{tag "effects"}
	{loudness "hit"}
	{file "/SOUND/Ricochet/ric_tree_bullet.wav"	"4"		}
	{file "/SOUND/Ricochet/ric_tree_bullet1.wav""5"		}
}
