;SDL
{"man_die"
	{tag "effects"}
	{loudness "talk"}
	{file "/sound/death/man_die_01.WAV"}
	{file "/sound/death/man_die_05.WAV"}
	{file "/sound/death/man_die_06.WAV"}
	{file "/sound/death/man_die_07.WAV"}
	{file "/sound/death/man_die_15.WAV"}
	{file "/sound/death/man_die_17.WAV"}
	{file "/sound/death/man_die_18.WAV"}
	{file "/sound/death/man_die_19.WAV"}
	{file "/sound/death/man_die_20.WAV"}
	{file "/sound/death/man_die_22.WAV"}
	{file "/sound/death/man_die_23.WAV"}
	{file "/sound/death/man_die_24.WAV"}
	{file "/sound/death/man_die_25.WAV"}
	{file "/sound/death/man_die_26.WAV"}
	{file "/sound/death/man_die_28.WAV"}
	{file "/sound/death/man_die_29.WAV"}
	{file "/sound/death/man_die_30.WAV"}
	{file "/sound/death/man_die_31.WAV"}
	{file "/sound/death/man_die_32.WAV"}
	{file "/sound/death/man_die_33.WAV"}
	{file "/sound/death/man_die_35.WAV"}
	{file "/sound/death/man_die_36.WAV"}
	{file "/sound/death/man_die_37.WAV"}
	{file "/sound/death/man_die_39.WAV"}
	{file "/sound/death/man_die_40.WAV"}
	{file "/sound/death/man_die_41.WAV"}
	{signal mandie 5}
}
{"man_hit"
	{tag "speak"}
	{loudness "talk"}
	{file "/sound/death/man_die_34.WAV"}
	{file "/sound/death/man_die_38.WAV"}
	{file "/sound/death/man_die_21.WAV"}
}
{"man_die_from_knife"
	{tag "speak"}
	{loudness "talk"}
	{file "/sound/death/man_die_02.WAV"}
	{file "/sound/death/man_die_03.WAV"}
	{file "/sound/death/man_die_04.WAV"}
	{file "/sound/death/man_die_08.WAV"}
	{file "/sound/death/man_die_09.WAV"}
	{file "/sound/death/man_die_10.WAV"}
	{file "/sound/death/man_die_13.WAV"}
	{file "/sound/death/man_die_34.WAV"}
	{file "/sound/death/man_die_16.WAV"}
	{file "/sound/death/man_die_27.WAV"}
	{signal movement 5}
}
{"man_blow"
	{tag "speak"}
	{loudness "talk"}
	{folder "/sound/hit/impact_human"}
	{signal movement 5}
}

{"talk"
	{tag "speak"}
	{loudness "talk"}
	{file "/SOUND/talks/english/cry_of_enthusiasm/skd74.wav"	"for_freedom"	{volume 0.6}}
	{file "/SOUND/talks/english/cry_of_enthusiasm/skd75.wav"	"charge"		{volume 0.6}}           
	{file "/SOUND/talks/english/assessment_explosion/skd111.wav" "alliluya"		{volume 0.6}}
	{file "/SOUND/talks/english/dismay/skd32.wav"				"no"			{volume 0.6}}
	{file "/SOUND/talks/english/triumph/skd38.wav" 	    		"whe_did_it"	{volume 0.6}}
	{file "/SOUND/talks/english/cry_of_enthusiasm/skd77.wav" 	"show"			{volume 0.6}}
	{file "/SOUND/talks/english/cry_for_help/skd97.wav" 		"help_en"		{volume 0.6}}
	{file "/SOUND/talks/american/cry_for_help/smd96.wav" 		"help_am00"		{volume 0.6}}
	{file "/SOUND/talks/american/cry_for_help/smd97.wav" 		"help_am01"		{volume 0.6}}
	{file "/SOUND/talks/american/exposition/smd61.wav" 			"surprise"		{volume 0.6}}
	{file "/SOUND/talks/german/throw_grenade/sgd83.wav" 		"throw_ger"		{volume 0.6}}
	{file "/SOUND/talks/german/cry_of_enthusiasm/sgd26.wav" 	"them_down_ger"	{volume 0.6}}
	{file "/sound/talks/german/cry_for_help\sgd53.wav"			"help1_ger"		{volume 0.6}}
	{file "/sound/talks/german/cry_for_help\sgd54.wav"			"help2_ger"		{volume 0.6}}
	{file "/sound/talks/german/cry_for_help\sgd55.wav"			"help3_ger"		{volume 0.6}}
	{file "/sound/talks/german/cry_for_help\sgd56.wav"			"help4_ger"		{volume 0.6}}
	{file "/sound/talks/german/cry_for_help\sgd57.wav"			"help5_ger"		{volume 0.6}}
	{file "/sound/talks/german/assessment_enemy_forces/sgd75.wav" "ger_charge"	{volume 0.6}}
	{file "/sound/talks/german/serious_things/sgd87.wav"		"ger_its_cant_be" {volume 0.6}}
}
