;SDL

(define "talk_sound"
	{"talk_%language_%folder"
		{tag "speak"}
		{folder "/sound/talks/%language/%folder"}
	}
)

("talk_sound" language(%language) folder(assessment_enemy_forces))
("talk_sound" language(%language) folder(assessment_explosion))
("talk_sound" language(%language) folder(cry_for_help))
("talk_sound" language(%language) folder(cry_of_content))
("talk_sound" language(%language) folder(cry_of_enthusiasm))
("talk_sound" language(%language) folder(cry_of_pain))
("talk_sound" language(%language) folder(dismay))
("talk_sound" language(%language) folder(evaluation))
("talk_sound" language(%language) folder(exposition))
("talk_sound" language(%language) folder(serious_things))
("talk_sound" language(%language) folder(throw_grenade))
("talk_sound" language(%language) folder(triumph))
