;SDL
{"pistol_shot"
	{tag "effects"}
	{loudness "shoot normal"}
	{file "/sound/shot/pistol/luger.WAV"		"luger"		}
	{file "/sound/shot/pistol/colt45.WAV"		"colt"		}
	{file "/sound/shot/pistol/valter.WAV"		"valter"	}
	{file "/sound/shot/pistol/nagan.WAV"		"nagan"		}
	{file "/sound/shot/pistol/tt.WAV"			"tt"		}
	{signal shot 15}
}
{"pistol_shot_silent"
	{tag "effects"}
	{loudness "shoot muted"}
	{file "/sound/shot/pistol/welrod.WAV"		"welrod"	}
	{signal movement 5}
}
{"smg_shot"
	{tag "effects"}
	{loudness "shoot normal"}
	{file "/sound/shot/smg/mp40.WAV"			"mp40"		}
	{file "/sound/shot/smg/sten.WAV"			"sten"		}
	{file "/sound/shot/smg/mp40.WAV"			"mp41"		}
	{file "/sound/shot/smg/mp44.WAV"			"mp44"		}
	{file "/sound/shot/smg/ppsh.WAV"			"ppsh"		}
	{file "/sound/shot/smg/thompson.WAV"		"thompson"	}
	{file "/sound/shot/gun/grnd_launch.wav"		"grenade"	}
	{signal shot 20}
}
{"mgun_shot"
	{tag "effects"}
	{loudness "shoot normal"}
	{file "/sound/shot/mgun/dt.WAV"				"dt"		}
	{file "/sound/shot/mgun/mg.WAV"				"mg34"		}
	{file "/sound/shot/mgun/mg_1.WAV"			"mg42"		}
	{file "/sound/shot/mgun/Maxim.WAV"			"maxim"		}
	{file "/sound/shot/mgun/browning.WAV" 		"browning"	}
	{file "/sound/shot/mgun/bren.WAV" 			"bren"		}
	{file "/sound/shot/mgun/bar.WAV" 			"bar"		}
	{signal shot 30}
}
{"rifle_shot"
	{tag "effects"}
	{loudness "shoot loud"}
	{file "/sound/shot/rifle/carabine.WAV"		"carabine"	}
	{file "/sound/shot/rifle/svt.WAV"			"svt"		}
	{file "/sound/shot/rifle/mosin.WAV"			"mosin"		}
	{file "/sound/shot/rifle/mauser98.WAV"		"mauzer"	}
	{file "/sound/shot/rifle/G41.WAV"			"g41"		}
	{file "/sound/shot/rifle/m1.WAV" 			"m1"		}
	{file "/sound/shot/rifle/m1carbine.WAV" 	"m1carbine"	}
	{file "/sound/shot/rifle/ptrs.wav"			"ptrs"		}
	{file "/sound/shot/rifle/enfield.wav"		"enfield"	}
	{signal shot 25}
}
{"heavy_shot"
	{tag "effects"}
	{loudness "shoot loud"}
	{file "/sound/shot/gun/zis3.wav"			"cannon"	}
	{file "/sound/shot/gun/EXPLOSIONBARREL.WAV"	"tank"		}
	{file "/sound/Shot/gun/shot37.wav"			"20mm"		}
	{file "/sound/Shot/gun/sam.wav"				"37mm"		}
	{file "/sound/Shot/gun/shot10.wav"			"45mm"		}
	{file "/sound/Shot/gun/shot04.wav"			"45mm"		}
	{file "/sound/Shot/gun/shot01.wav"			"50mm"		}
	{file "/sound/Shot/gun/shot75.wav"			"75mm"		}
	{file "/sound/Shot/gun/shot05.wav"			"76mm"		}
	{file "/sound/Shot/gun/shot07.wav"			"76a_mm"	}
	{file "/sound/Shot/gun/shot02.wav"			"85mm"		}
	{file "/sound/Shot/gun/shot88.wav"			"88mm"		}
	{file "/sound/Shot/gun/shot02.wav"			"122mm"		}
	{file "/sound/Shot/gun/shot02.wav"			"128mm"		}
	{file "/sound/Shot/gun/shot02.wav"			"152mm"		}
	{file "/sound/Shot/gun/shot150.wav"			"150mm"		}
	{file "/sound/Shot/gun/bm-13.wav"			"bm13"		}
	{file "/sound/Shot/gun/coastmortar.wav"		"203mm"		}
	{signal shot 50}
}
{"reload"
	{tag "effects"}
	{loudness "reload"}
	{file "/sound/reload/gun/smg.WAV"			"smg"		}
	{file "/sound/reload/gun/colt_r.WAV"		"colt_r"	}
	{file "/sound/reload/gun/sten_r.WAV"		"sten_r"	}
	{file "/sound/reload/gun/bar_r.WAV"			"bar_r"		}
	{file "/sound/reload/gun/rifle_r.WAV"		"rifle"		}
	{file "/sound/reload/gun/mg1_r.WAV"			"mg1_r"		}
	{file "/sound/reload/gun/dt1_r.WAV"			"dt1_r"		}
	{file "/sound/reload/gun/mp44_r.WAV"		"mp44_r"	}
	{file "/sound/reload/gun/m1_r.WAV"			"m1_r"		}
	{file "/sound/reload/gun/m1carbine_r.WAV"	"m1carbine_r"}
	{file "/sound/reload/gun/welrod_r.WAV"		"welrod_r"	}
	{file "/sound/reload/gun/pistol_r.WAV"		"pistol_r"	}
	{file "/sound/reload/gun/nagan_r.WAV"		"nagan_r"	}
	{file "/sound/reload/gun/webley_r.WAV"		"webley_r"	}
	{file "/sound/reload/gun/pak35_r.WAV"		"pak35_r"	}
	{file "/sound/reload/gun/ppsh_r.WAV"		"ppsh_r"	}
	{file "/sound/reload/gun/flak38_r.WAV"		"flak38_r"	}
	{file "/sound/reload/gun/ptrd_r.WAV"		"ptrd_r"	}
	{file "/sound/reload/gun/ptrs_r.WAV"		"ptrs_r"	}
	{file "/sound/reload/gun/gun_r00.WAV"		"gun_r00"	}
	{file "/sound/reload/gun/gun_r01.WAV"		"gun_r01"	}
	{file "/sound/reload/gun/gun_r02.WAV"		"gun_r02"	}
	{file "/sound/reload/gun/gun_r03.WAV"		"gun_r03"	}
}
