{weapon "mgun"
	{desc "mgun"}
	{item "mgun"}
	
	{level "none"
		{stand
			{accuracy 0.5}
		}
		{squat
			{accuracy 1}
		}
		{crawl
			{accuracy 1.5}
		}
		{cover
			{accuracy 1.2}
		}
	}

	{level "basic"
		{stand
			{accuracy 0.6}
		}
		{squat
			{accuracy 1.2}
		}
		{crawl
			{accuracy 1.8}
		}
		{cover
			{accuracy 1.6}
		}
	}
	{level "expert"
		{stand
			{accuracy 0.9}
		}
		{squat
			{accuracy 1.5}
		}
		{crawl
			{accuracy 2.5}
		}
		{cover
			{accuracy 2}
		}
	}
}
