{weapon "pistol"
	{desc "pistol"}
	{item "pistol"}
	{level "none"
		{stand
			{accuracy 0.5}
		}
		{squat
			{accuracy 1}
		}
		{crawl
			{accuracy 1.5}
		}
		{cover
			{accuracy 1.7}
		}
	}
	{level "basic"
		{stand
			{accuracy 1}
		}
		{squat
			{accuracy 1.3}
		}
		{crawl
			{accuracy 2.0}
		}
		{cover
			{accuracy 2.5}
		}
	}
    
	{level "expert"
		{stand
			{accuracy 1}
		}
		{squat
			{accuracy 1.3}
		}
		{crawl
			{accuracy 2.0}
		}
		{cover
			{accuracy 2.5}
		}
	}



}
