{weapon "rifle"
	{desc "rifle"}
	{item "rifle"}
	{level "none"
		{stand
			{accuracy 0.3}
		}
		{squat
			{accuracy 0.5}
		}
		{crawl
			{accuracy 1.0}
		}
		{cover
			{accuracy 0.7}
		}
	}
	{level "basic"
		{stand
			{accuracy 0.4}
		}
		{squat
			{accuracy 0.8}
		}
		{crawl
			{accuracy 1.2}
		}
		{cover
			{accuracy 1.0}
		}
	}
	{level "expert"
		{stand
			{accuracy 0.6}
		}
		{squat
			{accuracy 1.0}
		}
		{crawl
			{accuracy 1.8}
		}
		{cover
			{accuracy 1.6}
		}
	}
}
