{weapon "smg"
	{desc "smg"}
	{item "smg"}
	{level "none"
		{stand
			{accuracy 0.8}
		}
		{squat
			{accuracy 1}
		}
		{crawl
			{accuracy 1.3}
		}
		{cover
			{accuracy 1.2}
		}
	}
	{level "basic"
		{stand
			{accuracy 1}
		}
		{squat
			{accuracy 1.3}
		}
		{crawl
			{accuracy 1.8}
		}
		{cover
			{accuracy 1.6}
		}
	}

	{level "expert"
		{stand
			{accuracy 1.3}
		}
		{squat
			{accuracy 1.6}
		}
		{crawl
			{accuracy 2.0}
		}
		{cover
			{accuracy 1.8}
		}
	}
}
