{weapon "bazooka"
        {item "rocketlauncher"}

	{level "none"
		{stand
			{accuracy 0.2}
		}
		{squat
			{accuracy 0.4}
		}
		{cover
			{accuracy 0.5}
		}
	}
	{level "trained"
		{stand
			{accuracy 0.4}
		}
		{squat
			{accuracy 0.6}
		}
		{cover
			{accuracy 0.8}
		}
	}
        {level "basic"
		{stand
			{accuracy 0.6}
		}
		{squat
			{accuracy 0.8}
		}
		{cover
			{accuracy 1.0}
		}
	}
	{level "expert"
		{stand
			{accuracy 0.8}
		}
		{squat
			{accuracy 1.0}
		}
		{cover
			{accuracy 1.0}
		}
	}
}
