{weapon "MGUN_12.7"
	{item "MGUN_12.7"}
	
	{level "none"
		{stand
			{accuracy 0.01}
		}
		{squat
			{accuracy 0.2}
		}
		{crawl
			{accuracy 0.3}
		}
		{cover
			{accuracy 0.4}
		}
	}
	{level "trained"
		{stand
			{accuracy 0.05}
		}
		{squat
			{accuracy 0.4}
		}
		{crawl
			{accuracy 0.45}
		}
		{cover
			{accuracy 0.5}
		}
	}
	{level "basic"
		{stand
			{accuracy 0.1}
		}
		{squat
			{accuracy 0.55}
		}
		{crawl
			{accuracy 0.75}
		}
		{cover
			{accuracy 0.85}
		}
	}
	{level "expert"
		{stand
			{accuracy 0.2}
		}
		{squat
			{accuracy 0.8}
		}
		{crawl
			{accuracy 0.9}
		}
		{cover
			{accuracy 0.95}
		}
	}
}
