{weapon "mgun"
	{item "mgun"}
	
	{level "none"
		{stand
			{accuracy 0.05}
		}
		{squat
			{accuracy 0.3}
		}
		{crawl
			{accuracy 0.4}
		}
		{cover
			{accuracy 0.6}
		}
	}
	{level "trained"
		{stand
			{accuracy 0.1}
		}
		{squat
			{accuracy 0.5}
		}
		{crawl
			{accuracy 0.8}
		}
		{cover
			{accuracy 1.0}
		}
	}
	{level "basic"
		{stand
			{accuracy 0.4}
		}
		{squat
			{accuracy 1.0}
		}
		{crawl
			{accuracy 1.4}
		}
		{cover
			{accuracy 1.5}
		}
	}
	{level "expert"
		{stand
			{accuracy 0.6}
		}
		{squat
			{accuracy 1.2}
		}
		{crawl
			{accuracy 1.8}
		}
		{cover
			{accuracy 2.0}
		}
	}
}
