{weapon "pistol"
	{item "pistol"}
	
	{level "none"
		{stand
			{accuracy 0.2}
		}
		{squat
			{accuracy 0.4}
		}
		{crawl
			{accuracy 0.4}
		}
		{cover
			{accuracy 0.4}
		}
	}
	{level "trained"
		{stand
			{accuracy 0.4}
		}
		{squat
			{accuracy 0.6}
		}
		{crawl
			{accuracy 0.6}
		}
		{cover
			{accuracy 0.6}
		}
	}
	{level "basic"
		{stand
			{accuracy 0.6}
		}
		{squat
			{accuracy 0.8}
		}
		{crawl
			{accuracy 0.8}
		}
		{cover
			{accuracy 0.8}
		}
	}
	{level "expert"
		{stand
			{accuracy 1.8}
		}
		{squat
			{accuracy 2.0}
		}
		{crawl
			{accuracy 2.0}
		}
		{cover
			{accuracy 2.0}
		}
	}
}