{weapon "ptr"
	{item "ptr"}
	
	{level "none"
		{stand
			{accuracy 0.01}
		}
		{squat
			{accuracy 0.05}
		}
		{crawl
			{accuracy 0.4}
		}
		{cover
			{accuracy 0.4}
		}
	}
	{level "trained"
		{stand
			{accuracy 0.01}
		}
		{squat
			{accuracy 0.1}
		}
		{crawl
			{accuracy 0.6}
		}
		{cover
			{accuracy 0.6}
		}
	}
	{level "basic"
		{stand
			{accuracy 0.02}
		}
		{squat
			{accuracy 0.2}
		}
		{crawl
			{accuracy 0.8}
		}
		{cover
			{accuracy 0.8}
		}
	}
	{level "expert"
		{stand
			{accuracy 0.04}
		}
		{squat
			{accuracy 0.3}
		}
		{crawl
			{accuracy 0.9}
		}
		{cover
			{accuracy 1.0}
		}
	}
}
