{weapon "rifle"
	{item "rifle"}

	{level "none"
		{stand
			{accuracy 0.2}
		}
		{squat
			{accuracy 0.2}
		}
		{crawl
			{accuracy 0.4}
		}
		{cover
			{accuracy 0.4}
		}
	}

	
	{level "trained"
		{stand
			{accuracy 0.4}
		}
		{squat
			{accuracy 0.5}
		}
		{crawl
			{accuracy 0.6}
		}
		{cover
			{accuracy 0.6}
		}
	}
	{level "basic"
		{stand
			{accuracy 0.6}
		}
		{squat
			{accuracy 0.7}
		}
		{crawl
			{accuracy 0.9}
		}
		{cover
			{accuracy 0.9}
		}
	}
	{level "expert"
		{stand
			{accuracy 0.8}
		}
		{squat
			{accuracy 0.9}
		}
		{crawl
			{accuracy 1.0}
		}
		{cover
			{accuracy 1.0}
		}
	}
}