{weapon "smg"
	{item "smg"}

	{level "none"
		{stand
			{accuracy 0.3}
		}
		{squat
			{accuracy 0.4}
		}
		{crawl
			{accuracy 0.5}
		}
		{cover
			{accuracy 0.6}
		}
	}
	{level "trained"
		{stand
			{accuracy 0.5}
		}
		{squat
			{accuracy 0.55}
		}
		{crawl
			{accuracy 0.6}
		}
		{cover
			{accuracy 0.6}
		}
	}
	{level "basic"
		{stand
			{accuracy 0.65}
		}
		{squat
			{accuracy 0.7}
		}
		{crawl
			{accuracy 0.75}
		}
		{cover
			{accuracy 0.8}
		}
	}
	{level "expert"
		{stand
			{accuracy 0.85}
		}
		{squat
			{accuracy 0.9}
		}
		{crawl
			{accuracy 0.95}
		}
		{cover
			{accuracy 1.0}
		}
	}
}