{vision "vision"
	{level "human"
		{uncover 5}
		{h_fov 90}
		{v_fov 200}
		{human 35 {squat 30} {crawl 20}}
		{human 30 still {squat 25} {crawl 15}}
		{human 20 stealth {squat 15} {crawl 8}}
		{human 15 stealth still {squat 10} {crawl 4}}
		{actor 30}
                {actor "moto" 20}
                {actor "car" 30}
		{actor "cannon" 25}
		{actor "armored_car" 30}
		{actor "low" 35}
		{actor "average" 40}
		{actor "high" 45}
		{actor "huge" 55}
		{actor "marine" 30}
                {actor "airborne" 50}
		{fog_range 40}
		{fog_fov 90}
	}


	{level "mp_soldier"
		{uncover 10}
		{h_fov 95}
		{v_fov 200}
		{human 45 {squat 40} {crawl 25}}
		{human 40 still {squat 35} {crawl 20}}
		{human 30 stealth {squat 25} {crawl 11}}
		{human 25 stealth still {squat 20} {crawl 7}}
		{actor 40}
                {actor "moto" 30}
                {actor "car" 35}
		{actor "cannon" 35}
		{actor "armored_car" 40}
		{actor "low" 40}
		{actor "average" 45}
		{actor "high" 50}
		{actor "huge" 60}
		{actor "marine" 40}
                {actor "airborne" 50}
		{fog_range 45}
		{fog_fov 95}
	}

	{level "mp_prof_soldier"
		{uncover 15}
		{h_fov 100}
		{v_fov 200}
		{human 65 {squat 60} {crawl 35}}
		{human 55 still {squat 50} {crawl 25}}
		{human 45 stealth  {squat 35} {crawl 15}}
		{human 35 stealth still  {squat 30} {crawl 10}}
		{actor 50}
		{actor "cannon" 35}
                {actor "moto" 35}
                {actor "car" 40}
		{actor "armored_car" 50}
		{actor "low" 50}
		{actor "average" 55}
		{actor "high" 60}
		{actor "huge" 80}
		{actor "marine" 50}
                {actor "airborne" 50}
		{fog_range 55}
		{fog_fov 100}
	}

	{level "mp_officer"
		{uncover 55}
		{h_fov 50}
		{v_fov 200}
		{human 100 {squat 90} {crawl 50}}
		{human 90 still {squat 80} {crawl 45}}
		{human 55 stealth {squat 50} {crawl 40}}
		{human 50 stealth still {squat 45} {crawl 35}}
		{actor 80}
                {actor "moto" 50}
                {actor "car" 55}
		{actor "cannon" 60}
		{actor "low" 60}
		{actor "average" 75}
		{actor "high" 85}
		{actor "huge" 110}
		{actor "marine" 50}
                {actor "airborne" 50}
		{fog_range 100}
		{fog_fov 70}
	}

	{level "mp_general"
		{uncover 55}
		{h_fov 300}
		{v_fov 200}
		{human 140 {squat 90} {crawl 50}}
		{human 90 still {squat 80} {crawl 45}}
		{human 55 stealth {squat 50} {crawl 40}}
		{human 50 stealth still {squat 45} {crawl 35}}
		{actor 80}
                {actor "moto" 50}
                {actor "car" 55}
		{actor "cannon" 60}
		{actor "low" 60}
		{actor "average" 75}
		{actor "high" 85}
		{actor "huge" 110}
		{actor "marine" 50}
                {actor "airborne" 50}
		{fog_range 150}
		{fog_fov 300}
	}

	{level "mp_specnaz"
		{uncover 25}
		{h_fov 120}
		{v_fov 200}
		{human 70 {squat 65} {crawl 40}}
		{human 65 still {squat 60} {crawl 32}}
		{human 50 stealth {squat 45} {crawl 28}}
		{human 45 stealth still  {squat 40} {crawl 23}}
		{actor 60}
		{actor "armored_car" 55}
		{actor "low" 55}
		{actor "average" 60}
		{actor "high" 65}
		{actor "huge" 85}
		{actor "cannon" 40}
		{actor "marine" 60}
                {actor "airborne" 50}
		{fog_range 60}
		{fog_fov 120}
	}

	{level "mp_sniper"
		{uncover 65}
		{h_fov 12}
		{v_fov 200}
		{human 100 {squat 85} {crawl 55}}
		{human 90 still {squat 80} {crawl 45}}
		{human 65 stealth {squat 55} {crawl 40}}
		{human 55 stealth still  {squat 50} {crawl 30}}
		{actor 50}
		{actor "vehicle" 35}
		{actor "cannon" 50}
		{actor "marine" 40}
		{fog_range 100}
		{fog_fov 12}
	}

}