;SDL
{"death"
	{tag "effects"}
	{file "/sound/death/TANKDEATH.WAV"		"tank"		}
	{file "/sound/death/autodeath.WAV"		"machine"	}
	{file "/sound/death/housedead.wav"		"house"		}
	{file "/sound/death/TANKDEATH.WAV"		"barrels"	}
	{file "/sound/death/explo_end3.wav"		"falling_boards"}
	{file "/sound/death/rol_stone_br.WAV"	"br"		}
	{file "/sound/death/rolling_stone.WAV"	"st_big"	}
	{file "/sound/death/rolling_crush.WAV"	"crush"		}
	{file "/sound/death/wood_br.WAV"		"wood_br"	}
	{file "/sound/death/wood_br1.WAV"		"wood_br1"	}
	{file "/sound/death/wood_br2.WAV"		"wood_br2"	}
	{file "/sound/death/wood_br3.WAV"		"wood_br3"	}
	{file "/sound/death/wood_br5.WAV"	    "fence"		}
	{file "/sound/death/break_fence.WAV"	"fence01"	}
	{file "/sound/death/wood_br7.WAV"		"wood_br7"	}
	{file "/sound/death/wood_br8.WAV"		"wood_br8"	}
	{file "/sound/death/exp_wall00.wav"		"wall_br0"	}
	{file "/sound/death/exp_wall01.wav"		"wall_br1"	}
	{file "/sound/death/veh_crush00.wav"	"crush_car0"}
	{file "/sound/death/veh_crush01.wav"	"crush_car1"}
	{signal explosion 20}
}
{"death_tree"
	{tag "effects"}
	{file "/sound/death/break_tree.WAV"	 		"0"		}
	{file "/sound/death/break_tree1.WAV"	 	"1"		}
	{file "/sound/death/break_tree_small.WAV"	"2"		}
	{file "/sound/death/break_tree_small1.WAV"	"3"		}
}
{"death_veh"
	{tag "effects"}
	{file "/sound/death/veh_crush00.wav"				}
	{file "/sound/death/veh_crush01.wav"				}
}
{"tree_stir"
	{tag "environment"}
	{file "/sound/death/touch_tree.WAV"	 	{volume 0.7}}
	{file "/sound/death/touch_tree1.WAV"	{volume 0.7}}
	{file "/sound/death/touch_tree2.WAV"	{volume 0.7}}
	{file "/sound/death/touch_tree3.WAV"	{volume 0.7}}
	{file "/sound/death/touch_tree4.WAV"	{volume 0.7}}
}
