;SDL
{"engine"
	{tag "effects"}
	{file "/SOUND/engine/blitz_engine.wav" 			"blitz"		}
	{file "/SOUND/engine/blitz_engine_up.wav" 		"blitz_up"	}
	{file "/SOUND/engine/blitz_engine_end.wav"		"blitz_end"	}
	{file "/SOUND/engine/is_engine.wav" 			"is"		}
	{file "/SOUND/engine/is_engine_up.wav" 			"is_up"		}
	{file "/SOUND/engine/is_engine_end.wav"			"is_end"	}
	{file "/SOUND/engine/persch_engine.wav" 			"persch"		}
	{file "/SOUND/engine/persch_engine_up.wav" 			"persch_up"		}
	{file "/SOUND/engine/persch_engine_end.wav"			"persch_end"	}
	{file "/SOUND/engine/moto_engine.wav"			"moto"		}
	{file "/SOUND/engine/moto_engine_up.wav"		"moto_up"	}
	{file "/SOUND/engine/moto_engine_end.wav"		"moto_end"	}
	{file "/SOUND/engine/bmw_engine.wav"			"bmw"		}
	{file "/SOUND/engine/bmw_up.wav"				"bmw_up"	}
	{file "/SOUND/engine/tankengine.wav" 			"tank"		}
	{file "/SOUND/engine/tankengine_up.wav" 		"tank_up"	}
	{file "/SOUND/engine/tankengine_end.wav"		"tank_end"	}
	{file "/SOUND/engine/T-26_engine.wav" 			"t26"		}
	{file "/SOUND/engine/T-26_engine_up.wav" 		"t26_up"	}
	{file "/SOUND/engine/T-26_engine_end.wav"		"t26_end"	}
	{file "/SOUND/engine/bt_engine.wav" 			"bt"		}
	{file "/SOUND/engine/bt_engine_up.wav" 			"bt_up"		}
	{file "/SOUND/engine/bt_engine_end.wav"			"bt_end"	}
	{file "/SOUND/engine/M4_engine.wav" 			"m4"		}
	{file "/SOUND/engine/M4_engine_up.wav" 			"m4_up"		}
	{file "/SOUND/engine/M4_engine_end.wav"			"m4_end"	}
	{file "/SOUND/engine/M4a2_engine.wav" 			"m4a2"		}
	{file "/SOUND/engine/M4a2_engine_up.wav" 		"m4a2_up"	}
	{file "/SOUND/engine/M4a2_engine_end.wav"		"m4a2_end"	}
	{file "/SOUND/engine/m7_engine.wav" 			"m7"		}
	{file "/SOUND/engine/m7_engine_up.wav" 			"m7_up"		}
	{file "/SOUND/engine/m7_engine_end.wav"			"m7_end"	}
	{file "/SOUND/engine/jugdpnthr_engine.wav" 		"jdp"		}
	{file "/SOUND/engine/jugdpnthr_engine_up.wav"	"jdp_up"	}
	{file "/SOUND/engine/jugdpnthr_engine_end.wav"	"jdp_end"	}
	{file "/SOUND/engine/cromwell_engine.wav" 		"crmwll"	}
	{file "/SOUND/engine/cromwell_engine_up.wav" 	"crmwll_up"	}
	{file "/SOUND/engine/cromwell_engine_end.wav"	"crmwll_end"}
	{file "/SOUND/engine/panther_engine.wav" 			"panther"		}
	{file "/SOUND/engine/panther_engine_up.wav" 			"panther_up"		}
	{file "/SOUND/engine/panther_engine_end.wav" 			"panther_end"		}
	{file "/SOUND/engine/ferdi_engine.wav" 			"ferdi"		}
	{file "/SOUND/engine/ferdi_engine_up.wav" 			"ferdi_up"		}
	{file "/SOUND/engine/ferdi_engine_end.wav" 			"ferdi_end"		}
	{file "/SOUND/engine/pz6_engine.wav" 			"pz6"		}
	{file "/SOUND/engine/pz6_engine_up.wav" 		"pz6_up"	}
	{file "/SOUND/engine/pz6_engine_end.wav" 		"pz6_end"	}
	{file "/SOUND/engine/pz7_engine.wav" 			"pz7"		}
	{file "/SOUND/engine/pz7_engine_up.wav" 		"pz7_up"	}
	{file "/SOUND/engine/pz7_engine_end.wav" 		"pz7_end"	}
	{file "/SOUND/engine/heavy_engine.wav" 			"heavy"		}
	{file "/SOUND/engine/heavy_engine_up.wav" 		"heavy_up"	}
	{file "/SOUND/engine/heavy_engine_end.wav"		"heavy_end"	}
	{file "/SOUND/engine/hummel_engine.wav" 			"hummel"		}
	{file "/SOUND/engine/hummel_engine_up.wav" 		"hummel_up"	}
	{file "/SOUND/engine/hummel_engine_end.wav"		"hummel_end"	}
	{file "/SOUND/engine/su_engine.wav" 			"su"		}
	{file "/SOUND/engine/su_engine_up.wav" 		"su_up"	}
	{file "/SOUND/engine/su_engine_end.wav"		"su_end"	}
	{file "/SOUND/engine/isu_engine.wav" 			"isu"		}
	{file "/SOUND/engine/isu_engine_up.wav" 		"isu_up"	}
	{file "/SOUND/engine/isu_engine_end.wav"		"isu_end"	}
	{file "/SOUND/engine/pz2_engine.wav" 			"pz2"		}
	{file "/SOUND/engine/pz2_engine_up.wav" 		"pz2_up"	}
	{file "/SOUND/engine/pz2_engine_end.wav"		"pz2_end"	}
	{file "/SOUND/engine/pz3_engine.wav" 			"pz3"		}
	{file "/SOUND/engine/pz3_engine_up.wav" 		"pz3_up"	}
	{file "/SOUND/engine/pz3_engine_end.wav"		"pz3_end"	}
        
        {file "/SOUND/engine/pz38_engine.wav" 			"pz38"		}
	{file "/SOUND/engine/pz38_engine_up.wav" 		"pz38_up"	}
	{file "/SOUND/engine/pz38_engine_end.wav"		"pz38_end"	}

	{file "/SOUND/engine/pz4_engine.wav" 			"pz4"		}
	{file "/SOUND/engine/pz4_engine_up.wav" 		"pz4_up"	}
	{file "/SOUND/engine/pz4_engine_end.wav"		"pz4_end"	}
	{file "/SOUND/engine/hetzer_engine.wav" 			"hetzer"		}
	{file "/SOUND/engine/hetzer_engine_up.wav" 		"hetzer_up"	}
	{file "/SOUND/engine/hetzer_engine_end.wav"		"hetzer_end"	}
	{file "/SOUND/engine/kv_engine.wav" 			"kv"		}
	{file "/SOUND/engine/kv_engine_up.wav" 			"kv_up"		}
	{file "/SOUND/engine/kv_engine_end.wav"			"kv_end"	}
	{file "/SOUND/engine/ba20_engine.wav" 			"ba20"		}
	{file "/SOUND/engine/ba20_engine_up.wav" 		"ba20_up"	}
	{file "/SOUND/engine/ba20_engine_end.wav"		"ba20_end"	}
        {file "/SOUND/engine/m3a1_engine.wav" 			"m3a1"		}
	{file "/SOUND/engine/m3a1_engine_up.wav" 		"m3a1_up"	}
	{file "/SOUND/engine/m3a1_engine_end.wav"		"m3a1_end"	}
	{file "/SOUND/engine/sdkfz232_engine.wav" 		"sd232"		}
	{file "/SOUND/engine/sdkfz232_engine_up.wav" 	"sd232_up"	}
	{file "/SOUND/engine/sdkfz232_engine_end.wav"	"sd232_end"	}
	{file "/SOUND/engine/sdkfz234_engine.wav" 		"sd234"		}
	{file "/SOUND/engine/sdkfz234_engine_up.wav" 	"sd234_up"	}
	{file "/SOUND/engine/sdkfz234_engine_end.wav"	"sd234_end"	}
	{file "/SOUND/engine/sdkfz250_engine.wav" 		"sd250"		}
	{file "/SOUND/engine/sdkfz250_engine_up.wav" 	"sd250_up"	}
	{file "/SOUND/engine/sdkfz250_engine_end.wav"	"sd250_end"	}
	{file "/SOUND/engine/t34_engine.wav" 			"t34"		}
	{file "/SOUND/engine/t34_engine_up.wav" 		"t34_up"	}
	{file "/SOUND/engine/t34_engine_end.wav"		"t34_end"	}
	{file "/SOUND/engine/t3485_engine.wav" 			"t3485"		}
	{file "/SOUND/engine/t3485_engine_up.wav" 		"t3485_up"	}
	{file "/SOUND/engine/t3485_engine_end.wav"		"t3485_end"	}
	{file "/SOUND/engine/car_engine.wav"			"car"		}
	{file "/SOUND/engine/car_engine_up.wav"			"car_up"	}
	{file "/SOUND/engine/car_engine_end.wav"		"car_end"	}
	{file "/SOUND/engine/MB_engine.wav"				"MB"		}
	{file "/SOUND/engine/MB_engine_up.wav"			"MB_up"		}
	{file "/SOUND/engine/MB_engine_end.wav"			"MB_end"	}
	{file "/SOUND/engine/Dodge_engine.wav"			"Dodge"		}
	{file "/SOUND/engine/Dodge_engine_up.wav"		"Dodge_up"	}
	{file "/SOUND/engine/Dodge_engine_end.wav"		"Dodge_end"	}
	{file "/SOUND/engine/kubel_engine.wav"			"kubel"		}
	{file "/SOUND/engine/kubel_engine_up.wav"		"kubel_up"	}
	{file "/SOUND/engine/kubel_engine_end.wav"		"kubel_end"	}
	{file "/SOUND/engine/horch_engine.wav"			"horch"		}
	{file "/SOUND/engine/horch_engine_up.wav"		"horch_up"	}
	{file "/SOUND/engine/horch_engine_end.wav"		"horch_end"	}
	{file "/SOUND/engine/GMC_engine.wav"			"gmc"		}
	{file "/SOUND/engine/GMC_engine_up.wav"			"gmc_up"	}
	{file "/SOUND/engine/GMC_engine_end.wav"		"gmc_end"	}
	{file "/SOUND/engine/Opel_engine.wav"			"Opel"		}
	{file "/SOUND/engine/Opel_engine_up.wav"		"Opel_up"	}
	{file "/SOUND/engine/Opel_engine_end.wav"		"Opel_end"	}
	{file "/SOUND/engine/truck_engine.wav"			"truck"		}
	{file "/SOUND/engine/truck_engine_up.wav"		"truck_up"	}
	{file "/SOUND/engine/truck_engine_end.wav"		"truck_end"	}
	{file "/SOUND/engine/sdkfz_engine.wav"			"sdkfz"		}
	{file "/SOUND/engine/sdkfz_engine_up.wav"		"sdkfz_up"	}
	{file "/SOUND/engine/sdkfz_engine_end.wav"		"sdkfz_end"	}
	{file "/SOUND/engine/sdkfz10_engine.wav"		"sd10"  	}
	{file "/SOUND/engine/sdkfz10_engine_up.wav" 	"sd10_up"	}
	{file "/SOUND/engine/sdkfz10_engine_end.wav"    "sd10_end"	}
	{file "/SOUND/engine/zis_engine.wav"			"zis"		}
	{file "/SOUND/engine/zis_engine_up.wav"			"zis_up"	}
	{file "/SOUND/engine/zis_engine_end.wav"		"zis_end"	}
	{file "/SOUND/engine/lct_engine_up.wav"			"lct_up"	}
	{file "/SOUND/engine/lct_engine_end.wav"		"lct_end"	}
	{file "/SOUND/engine/d3_engine.wav"				"d3"		}
	{file "/SOUND/engine/d3_engine_up.wav"			"d3_up"		}
	{file "/SOUND/engine/d3_engine_end.wav"			"d3_end"	}
	{file "/SOUND/engine/door.wav"					"gate_open"	}
	{file "/SOUND/engine/airbag_engine.wav" 		"airbag"	}
	{file "/SOUND/engine/airbag_engine_up.wav" 		"airbag_up"	}
	{file "/SOUND/engine/airbag_engine_end.wav"		"airbag_end"}
	{signal movement 12}
}
{"turret"
	{tag "effects"}
	{file "/SOUND/engine/turret.wav"				"flak"		}
	{file "/SOUND/engine/turret_t.wav"				"t34"		}
	{file "/SOUND/engine/turret_is.wav"				"is2"		}	
	{file "/SOUND/engine/turret1.wav"				"mortar"	}
	{file "/SOUND/engine/hturret_rot1.wav"			"hturret1"	}
	{file "/SOUND/engine/hturret_rot2.wav"			"hturret2"	}
	{file "/SOUND/engine/hturret_rot3.wav"			"hturret3"	}
	{file "/SOUND/engine/hturret_rot4.wav"			"hturret4"	}
	{file "/SOUND/engine/hturret_rot5.wav"			"hturret5"	}
	{file "/SOUND/engine/hturret_rot6.wav"			"hturret6"	}
	{file "/SOUND/engine/hturret_rot7.wav"			"hturret7"	}
	{file "/SOUND/engine/lturret00.wav"				"lturret00"	}
	{file "/SOUND/engine/lturret01.wav"				"lturret01"	}
        {file "/SOUND/engine/turret_is.wav"				"turret_is"	}
        {file "/SOUND/engine/turret_sm.wav"				"turret_sm"	}
	{signal movement 5}
}
{"tracks"
	{tag "effects"}
	{file "/SOUND/engine/bt_move.wav" 				"bt_move"	}
	{file "/SOUND/engine/trackclank00.wav" 			"move00"	}
	{file "/SOUND/engine/trackclank01.wav" 			"move01"	}
    	{file "/SOUND/engine/cromwell_move.wav"        "crmwll_move"}
	{file "/SOUND/engine/heavy_clank.wav" 			"heavy_move"}
	{file "/SOUND/engine/tank_clank.wav" 			"tank_move"	}
	{file "/SOUND/engine/pz2_move.wav" 		    	"pz2_move"  }
	{file "/SOUND/engine/pz3_move.wav" 		    	"pz3_move"  }
	{file "/SOUND/engine/pz4_move.wav" 		    	"pz4_move"  }
	{file "/SOUND/engine/pz7_move.wav" 		    	"pz7_move"  }
	{file "/SOUND/engine/panther_move.wav" 		    	"panther_move"  }
	{file "/SOUND/engine/persch_move.wav" 		    	"persch_move"  }
	{file "/SOUND/engine/su_move.wav" 		    	"su_move"  }
	{file "/SOUND/engine/isu_move.wav" 		    	"isu_move"  }
	{file "/SOUND/engine/kv_clank.wav" 				"kv_move"	}
   	{file "/SOUND/engine/m3a1_move.wav" 			"m3a1_move" }
	{file "/SOUND/engine/t34_clank.wav" 			"t34_move"	}
	{file "/SOUND/engine/t3485_clank.wav" 			"t3485_move"}
	{file "/SOUND/engine/m4_move.wav" 				"m4_move"	}
	{file "/SOUND/engine/m4a2_move.wav" 			"m4a2_move"	}
	{file "/SOUND/engine/m7_move.wav" 				"m7_move"	}
	{file "/SOUND/engine/jugdpnthr_move.wav" 		"jdp_move"	}
	{file "/SOUND/engine/jugdpnthr_move.wav" 		"jgdp_move"	}
	{file "/SOUND/engine/sdkfz10_move.wav" 			"sd10_move"	}
	{file "/SOUND/engine/sdkfz234_move.wav" 		"sd234_move"}
	{file "/SOUND/engine/sdkfz10_move.wav" 			"sd250_move"}
	{file "/SOUND/engine/is_move.wav" 				"is_move"	}
	{signal movement 15}
	{SignalPeriod 1}
}
{"wheels"
	{tag "effects"}
	{file "/SOUND/engine/Blitz_move.wav" 			"blitz_move"		}
	{file "/SOUND/engine/Dodge_move.wav" 			"dodge_move"		}
	{file "/SOUND/engine/bmw_move.wav" 				"bmw_move"			}
	{file "/SOUND/engine/bmw_move_end.wav" 			"bmw_end"			}
	{file "/SOUND/engine/GMC_move.wav" 				"gmc_move"			}
	{file "/SOUND/engine/GMC_move_end.wav" 			"gmc_end"			}
	{file "/SOUND/engine/car_move.wav" 				"move"				}
	{file "/SOUND/engine/GMC_move_end.wav" 			"gmc_move_end"		}
	{file "/SOUND/engine/GMC_move_end.wav" 			"gmc_end"			}
	{file "/SOUND/engine/car_move_end.wav" 			"move_end"			}
	{file "/SOUND/engine/MB_move.wav" 				"MB_move"			}
	{file "/SOUND/engine/kubel_move.wav" 			"kubel_move"		}
	{file "/SOUND/engine/horch_move.wav" 			"horch_move"		}
	{file "/SOUND/engine/Opel_move.wav" 			"Opel_move"		    }
	{file "/SOUND/engine/Opel_move_end.wav" 		"Opel_move_end"		}
	{file "/SOUND/engine/truck_move.wav" 			"truck_move"		}
	{file "/SOUND/engine/truck_move_end.wav" 		"truck_move_end"	}
	{file "/SOUND/engine/sdkfz_move.wav" 			"sdkfz_move"		}
	{file "/SOUND/engine/sdkfz_move_end.wav" 		"sdkfz_move_end"	}
	{file "/SOUND/engine/sdkfz10_move.wav" 			"sd10_move"  		}
	{file "/SOUND/engine/sdkfz234_move.wav" 		"sd234_move"		}
	{file "/SOUND/engine/sdkfz250_move.wav" 		"sd250_move"		}
	{file "/SOUND/engine/d3_move.wav" 				"d3_move"			}
	{file "/SOUND/engine/d3_move_end.wav" 			"d3_move_end"		}
	{file "/SOUND/engine/train_move.wav" 			"locomotive_move"	}
	{file "/SOUND/engine/train_brake.wav"	 		"locomotive_brake"	}
	{file "/SOUND/engine/train_accelerate.wav"	 	"locomotive_acc"	}
	{file "/SOUND/engine/wheels.wav" 				"wheels_rot"		}
	{file "/SOUND/engine/wheels1.wav" 				"wheels_rot1"		}
	{file "/SOUND/engine/lct_move.wav" 				"lct_move"			}
	{file "/SOUND/engine/lct_move_end.wav" 			"lct_move_end"		}
	{file "/SOUND/engine/cargo_move.wav" 			"cargo_move"		}
	{file "/SOUND/engine/engine_boat.wav" 			"engine_boat"		}
	{file "/SOUND/engine/siren_boat.wav" 			"siren_boat"		}
	{signal movement 8}
	{SignalPeriod 1}
}
{"airborne"
	{tag "effects"}
	{file "/SOUND/engine/fw_work.wav" 				"fw_move"			}
	{file "/SOUND/engine/fw_move.wav" 				"fw_work"			}
	{file "/SOUND/engine/fw_start.wav" 				"fw_start"			}
	{file "/SOUND/engine/fw_stop.wav" 				"fw_stop"			}
	{file "/SOUND/engine/fw_deep.wav" 				"fw_deep"			}
	{file "/SOUND/engine/p51_move.wav" 				"p51_move"			}
	{file "/SOUND/engine/p51_work.wav" 				"p51_work"			}
	{file "/SOUND/engine/p51_start.wav" 			"p51_start"			}
	{signal movement 50}
	{SignalPeriod 0.5}
}
{"reactive"
	{tag "effects"}
	{file "/SOUND/shot/rocket.wav" 					"katusha_ammo"		}
	{file "/SOUND/shot/rocket_deep.wav" 			"ammo_deep"			}
	{signal movement 20}
	{SignalPeriod 0.5}
}
{"human"
	{tag "effects"}
	{file "/sound/world/running.wav"				"move"				}
	{file "/sound/world/swimming.wav"				"swim"				}
	{file "/SOUND/world/run.wav" "move"}
	{signal movement 4}
	{SignalPeriod 0.5}
}
