{DecalView
	{ownershadow sublocal 64 64}
	{Sprite "human.ebm"
		{Scale 0.8 }
		{Visibility 0.5}
	}
	{name "shadow"}
	{UseDirection}
	{Layer groundshadow}
}
{DecalView
	{ownershadow local 64 64}
	{name "shadow1"}
}

;{DecalView "shadow"
;	{ownershadow sublocal 64 64}
;	{Sprite "human.ebm"
;		{Scale 0.8 }
;		{Visibility 0.5}
;	}
;	{UseDirection}
;	{Layer groundshadow}
;}
;{DecalView "shadow1"
;	{ownershadow local 64 64}
;	{Sprite "human.ebm"
;		{Scale 0.8 }
;		{Visibility 0.5}
;	}
;}
